version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: backend_challenge
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend_user -d backend_challenge"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: ["/start.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: backend_challenge.production_settings
      DJANGO_DB_ENGINE: django.db.backends.postgresql
      DJANGO_DB_NAME: backend_challenge
      DJANGO_DB_USER: backend_user
      DJANGO_DB_PASSWORD: backend_pass
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_SECRET_KEY: super-secret-key
      DJANGO_DEBUG: "True"

volumes:
  pgdata:
